### ISSUE TITLE
Provide a YAML parser to initialize a streamiz instance

### ISSUE THREAD

**Issue by LGouellec** [LGouellec/kafka-streams-dotnet#226]
Description
===========

For now, the configuration is passed by a `StreamConfig` instance. 

The aim of this issue is to provide a YAML parser to parse a yaml file and get a `StreamConfig` instance directly.
This parser must also take into account the environment variables (with priority maybe)

```yaml
# Streamiz property
stream:
  bootstrap.servers: "localhost:9092"
  application.id: "test-app"
# Client property for instance (sasl.username, sasl.password, etc ...)
client:
# Consumer property for instance (auto.offset.reset, ...)
consumer:
# Producer property for instance (acks, ...)
producer:
```
